build:
  cuda_version: "12.1.1"
  python_packages:
    - torch==2.6.0
    - transformers==4.48.2
    - accelerate==1.3.0
    - soundfile==0.13.1
    - pillow==11.1.0
    - scipy==1.15.2
    - torchvision==0.21.0
    - backoff==2.2.1
    - peft==0.13.2
    - hf-transfer==0.1.9
    - inferless==0.2.13
    - pydantic==2.10.2
  run:
    - "pip install flash_attn==2.7.4.post1"
